### ISSUE TITLE
NPSSO not working

### ISSUE THREAD

**Issue by gent00** [XenorPLxx/playnite-library-psn#12]
Using latest library and Playrite. I am loging in and entering NPSSO value (Yes XXX part). And when i click check auth it gives "requires auth" error.

**Comment by XenorPLxx** [comment]
You can try the legacy authentication method (on the bottom of the config screen), I had reports from users that NPSSO doesn't work, but legacy still does for them.

**Comment by gent00** [comment]
Yes i just wanted to send a bug report. Also we do read them :) :

![121](https://user-images.githubusercontent.com/5721191/205634230-b02bd7f5-59b3-44bd-83ea-02b4e40b48dd.png)

Thanks for your efforts btw.

**Comment by XenorPLxx** [comment]
@gent00 when you log in PSN through browser, do you click 'Trust this Browser'? That might be one of the things causing issues with this method.

**Comment by nagromc** [comment]
I stumbled upon the same issue, and yes I checked the _Trust this browser_ checkbox.

When I try the _Legacy authentication method_, a popup window is displayed in Playnite briefly showing the PlayStation website, and then closes. The label _Checking authentication status…_ is shown next to the button _Check Authentication_, but then shows _Requires authentication_ again.

**Comment by eskypi** [comment]
It still doesn't work for me, I've tried both methods and neither works. Is there any solution?

**Comment by XenorPLxx** [comment]
@nagromc, @eskypi - try version 2.19 of the add-on.

**Comment by gent00** [comment]
Thanks
