### ISSUE TITLE
Failed to import games from PlayStation.

### ISSUE THREAD

**Issue by finkleroy** [XenorPLxx/playnite-library-psn#16]
Every time I launch Playnite, I get the following error: "Failed to import games from PlayStation. Value cannot be null. Parameter name: collection". It says I'm authenticated, and I haven't changed any settings in months. I generated a diagnostic package, which gave me this code: 291cebc8-1136-448e-8aba-fcf7ade1ee35.

**Comment by Derko1** [comment]
I am getting the same exact error as well. I thought it might have been an authentication issue and authenticated multiple times and different ways. No luck though.

**Comment by finkleroy** [comment]
> Fixed in https://github.com/XenorPLxx/playnite-library-psn/releases/tag/2.21

Works now. Thanks for the quick fix!
