### ISSUE TITLE
Failed to import PSN games. System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by LukePeltier** [XenorPLxx/playnite-library-psn#17]
**Describe the bug**
When attempting to update library (new library, never imported PSN before), i receive this error and no import is done.

**To Reproduce**
Attempt to update PSN library

**Screenshots**
![image](https://user-images.githubusercontent.com/18688112/234383399-667eafd0-71b8-4ce6-839f-33bda74ae8d5.png)
![image](https://user-images.githubusercontent.com/18688112/234383522-a9d79e9f-d5ed-4632-8ab8-f0c90d6fb34a.png)

**Diagnostics ID**
167e277d-8607-4b92-91a8-90ed271a0f8d

**Comment by eskypi** [comment]
The same thing happens to me... :(
