### ISSUE TITLE
PSN: Played games list couldn't be parsed.

### ISSUE THREAD

**Issue by finkleroy** [XenorPLxx/playnite-library-psn#18]
Ever since the most recent update, I now get the following error: "PSN: Played games list couldn't be parsed.". The diagnostic code is d25471e9-af36-4570-89bc-7ad94dd30c96.

**Comment by asgump** [comment]
+1

**Comment by XenorPLxx** [comment]
Yea, that's a direct result of problem reported in https://github.com/XenorPLxx/playnite-library-psn/issues/17 and bypassed in https://github.com/XenorPLxx/playnite-library-psn/releases/tag/2.22.

One of the Sony APIs stopped responding and throws a non-descriptive error. It shouldn't impact plugin operation, as it uses 3 APIs total to collect games and most of them are present in all 3 APIs.

**Comment by finkleroy** [comment]
> Yea, that's a direct result of problem reported in #17 and bypassed in https://github.com/XenorPLxx/playnite-library-psn/releases/tag/2.22.
> 
> One of the Sony APIs stopped responding and throws a non-descriptive error. It shouldn't impact plugin operation, as it uses 3 APIs total to collect games and most of them are present in all 3 APIs.

Ahh. Gotcha. I hadn't received that error until now. It's good to know it's nothing to worry about.
