### ISSUE TITLE
All PSN APIs Are Down

### ISSUE THREAD

**Issue by finkleroy** [XenorPLxx/playnite-library-psn#20]
Playnite reports that all four PSN APIs are unresponsive. I get an error for each of them. Can anybody check if they're actually down, or if they've changed how they work yet again, which would require an update to the integration to get things working again? I don't know if this is relevant, but I was able to log out and back into my PlayStation account on their website using Chrome in Windows 10.

**Comment by finkleroy** [comment]
The issue persists.

**Comment by XenorPLxx** [comment]
@finkleroy go to plugin settings and click the URL in the second point (or here: https://ca.account.sony.com/api/v1/ssocookie).
Authentication check seems to be broken currently, you probably just got logged out and need to replace the SSO token.

**Comment by finkleroy** [comment]
Thanks. That fixed it. I didn't think to update the token because it said I was still authenticated.
