### ISSUE TITLE
Option to Set Source of "Playstation Plus" games to "Playstation Plus"

### ISSUE THREAD

**Issue by joyrider3774** [XenorPLxx/playnite-library-psn#23]
**Describe the solution you'd like**
Add an options to set Source of "Playstation Plus" games to "Playstation Plus" that way when people group on source instead of the default by library they can easily differentiate between owned games and plus games.

**Screenshots**
![image](https://github.com/XenorPLxx/playnite-library-psn/assets/10714776/ba9769e4-f6d0-4caf-8c3d-70a93735b279)

**Comment by XenorPLxx** [comment]
@joyrider3774:
- Addon options now have a flag to 'Set a separate source for PlayStation Plus games'
![image](https://github.com/XenorPLxx/playnite-library-psn/assets/6712823/18b6875c-f651-4f61-8508-8825e3a0c3f3)
- It will flip source for all existing PS Plus games and respect it for new games, manual changes will be overwritten
- New games with unknown source (e.g. PS3, possibly disk games) are added as 'PlayStation', but manual changes will not be overwritten
- Digital version has more priority (e.g. digital PS Plus and owned disk == game has PlayStation Plus Source) - no way to tell ownership of disk games, those show up on played games list same way as ps plus games, not tagged there
- When flag is unchecked, it will flip every game back to 'PlayStation'

**Comment by joyrider3774** [comment]
thanks will try it out later :)

**Comment by sygmakikus** [comment]
> * Addon options now has a flag to 'Set a separate source for PlayStation Plus games'

Hi, I've been testing thos new option with no luck. I am still getting a lot of PS Plus games (even though currently I have no active suscription) unther the "Playstation" source and I am not seeing any "Playstation Plus" source either.

I currently have the same config as @XenorPLxx's screenshot

I tried removing the library, uninstalling the integration but I always get the same result. What may I be doing wrong?

**Comment by berkayfeci** [comment]
> > * Addon options now has a flag to 'Set a separate source for PlayStation Plus games'
> 
> Hi, I've been testing this new option with no luck. I am still getting a lot of PS Plus games under the "Playstation" source and I am not seeing any "Playstation Plus" source either.
> 
> I currently have the same config as @XenorPLxx's screenshot.
> 
> I tried removing the library, uninstalling the integration but I always get the same result. What may I be doing wrong?

Are you sure you are filtering by source instead of library? I was confused too and thought it didn't work but source section is separate from library.
