### ISSUE TITLE
Addon crashes my Playnite entirely

### ISSUE THREAD

**Issue by profucius** [XenorPLxx/playnite-library-psn#27]
For some reason, when I install your Playstation integration addon, then go into the settings to configure it, moments later the entire Playnite app will crash. This was not an issue a few months ago, I then recently updated to latest version, and now the crashing began.

I have tried fully uninstalling the addon, and deleting the addon data, then reinstalling it. Crashing still occurs. 

The crash happens within 2-3 seconds of opening the addon settings window. I can see the addon settings, and if I hover over any tickbox it seems responsive for about 1 second. Then it becomes unresponsive for another second or two, then the entire app crashes.

Playnite does not give me a crash diagnostic, so this is a full diagnostic from About Playnite window:
`dd9d2731-e255-4397-bdd4-7f08453d5828`

Windows 11 (latest)
Playnite 10.32 (latest)
Your addon 2.31 (latest)

**Comment by XenorPLxx** [comment]
Uh this reminds me I need to update the bug template, I don't actually have access to diagnostics, this is copied over from Playnite maintainers repo. In Playnite data folder (you can access it trough menu->about->data or smt like that) there's and extension.log file, let's start by looking at that - I'll be able to see where it fails and compile a version with some extra debugging info.

If there's no crash dialogue, then chances are there might be no logs too.

One other thing you can try is to delete plugin data and then also clear cache (menu/settings/advanced/clear web cache). That would also trigger a restart, and all PSN authentication data should be completely gone this way.

**Comment by profucius** [comment]
The crashing no longer occurs. I'm not sure why. I put off diagnosing it for the past two weeks, and I saw there was an update a few days ago. I also completely removed and reinstalled the addon (I tried doing that before and it didn't help). Anyway I am glad it works. I'll close the ticket. Thanks
