### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by erbilnas** [XenorPLxx/playnite-library-psn#29]
**Describe the bug**
Every time I attempt to authenticate my PS account, it displays a 'too many requests' error. However, I'm only attempting to recheck once a day. (PSNLibrary.dll Version 2.32)

**Screenshots**
![image](https://github.com/XenorPLxx/playnite-library-psn/assets/15656271/7371a353-c580-4c0c-b705-988e7dce5448)

**Comment by maicol07** [comment]
I've found a workaround/fix: go to the account management page and login if you are not already logged in. Then open DevTools (F12 or CTRL+SHIFT+I), go to Application --> Cookie --> https://id.sonyentertainmentnetwork.com and copy the value of the `npsso` cookie. Enter this value in Playnite and you'll be authenticated!

**Comment by erbilnas** [comment]
Yes, it works wonderfully! Thank you so much, I really appreciate it. <3
