### ISSUE TITLE
"HTTP Status 429 – Too Many Requests" error on authentication

### ISSUE THREAD

**Issue by HaarisQureshi** [XenorPLxx/playnite-library-psn#32]
Hello
Authentication has not been working for a few days, the [ssocookie](https://ca.account.sony.com/api/v1/ssocookie) site returns a HTTP Status 429 – Too Many Requests. 
Thanks

**Comment by XenorPLxx** [comment]
@HaarisQureshi I've had success with clearing out cookies in the browsers and logging in again on PSN before accessing ssocookie. Here's someones https://github.com/XenorPLxx/playnite-library-psn/issues/22#issuecomment-2096318109 who also did something similar.

Unfortunately, not much I can do about PSN behaving this way in the browser. They are blocking embedded browsers, and now they are trying to block this way of authentication too.

**Comment by HaarisQureshi** [comment]
Ah thanks! Yes I did this in Incognito and it worked.
Hopefully that work around continues!
