### ISSUE TITLE
PSN library not authenticating

### ISSUE THREAD

**Issue by Blue-Meanie** [XenorPLxx/playnite-library-psn#35]
**Check for existing issue**
Nothing found

**Describe the bug**
PSN integration shows as user not authenticated, even after refreshing the NPSSO token multiple times

**To Reproduce**
Sign into PSN website, go to https://ca.account.sony.com/api/v1/ssocookie and paste code into PlayNite, click "check authentication"

**Screenshots**
![image](https://github.com/user-attachments/assets/3953500c-4d53-43b6-8cfe-243bc4124ed9)
![image](https://github.com/user-attachments/assets/ae3e64c1-dfa5-47bf-96b3-b1ad46f82ae6)

**Diagnostics ID**
[playnite.log](https://github.com/user-attachments/files/16539069/playnite.log)

**Comment by henryadamsjr** [comment]
I'm having the same issue, and I don't see anything useful in the logs even with trace on.

**Comment by finkleroy** [comment]
I'm having the same issue.

**Comment by XenorPLxx** [comment]
Fixed in https://github.com/XenorPLxx/playnite-library-psn/releases/tag/2.34
