### ISSUE TITLE
Failed to import games from PlayStation (import issues)

### ISSUE THREAD

**Issue by XenorPLxx** [XenorPLxx/playnite-library-psn#6]
```log
Failed to import games from PlayStation. Unexpected character encountered while parsing value: <. Path ", line 0, position 0.
```

![image](https://user-images.githubusercontent.com/6712823/196650444-80472c20-f4d7-445b-90fb-d9c4cdd45603.png)

_Originally posted by @finkleroy in https://github.com/XenorPLxx/playnite-library-psn/issues/5#issuecomment-1283455060_

**Comment by XenorPLxx** [comment]
Getting this on the game list endpoint:
```
<HTML>

<HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD>

<BODY>\n<H1>Access Denied</H1>\n \nYou don't have permission to access \"http&#58;&#47;&#47;m&#46;np&#46;playstation&#46;net&#47;api&#47;gamelist&#47;v2&#47;users&#47;me&#47;titles&#63;\" on this
    server.<P>\nReference&#32;&#35;18&#46;4d5b6068&#46;1666172949&#46;3feab2bd\n</BODY>\n

</HTML>\n
```

**Comment by XenorPLxx** [comment]
Fixed in https://github.com/XenorPLxx/playnite-library-psn/releases/tag/2.14

**Comment by eskypi** [comment]
Same Error, it is not fixed in the new version :( help

**Comment by XenorPLxx** [comment]
Are you sure it's exactly the same message? I'm seeing reports of an import error that I can reproduce, but message should be different.

**Comment by eskypi** [comment]
![image](https://user-images.githubusercontent.com/89943859/198738401-2397a41f-1db7-4d9e-911b-a4b02de5a53b.png)

an hour ago the same error came out, now the error text has changed

**Comment by XenorPLxx** [comment]
Yea, I was just getting into debugging this and then the error disappeared, so I suspect some instability with the API. I'll still try to do some better logging for next time, but for now I'm not seeing the error anymore.
